//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphont_LTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Nullable<int> C_id { get; set; }
        public int B_id { get; set; }
        public string Book_Name { get; set; }
        public string Book_PDF { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
