//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphont_LTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Nullable<int> ID { get; set; }
        public int E_id { get; set; }
        public string Exam_Name { get; set; }
        public Nullable<System.TimeSpan> Exam_Time { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
