//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphont_LTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public Nullable<int> ID { get; set; }
        public int F_id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
